development:
  adapter: postgresql
  database: shakaihoshou
  pool: 5
  timeout: 5000
  username: halfdan-rump

test:
  adapter: postgresql
  database: shakaihoshou
  pool: 5
  timeout: 5000
  username: halfdan-rump


stage:
  adapter: postgresql
  database: shakaihoshou
  pool: 5
  timeout: 5000
  username: halfdan-rump

production:
  adapter: postgresql
  database: shakaihoshou
  pool: 5
  timeout: 5000
  username: halfdan-rump