# encoding: utf-8
class DropInstitutionsTable < ActiveRecord::Migration
  def change
  	drop_table :institutions
 #  	rename_column :institutions, :"都、国、市町村", :"0"
	# rename_column :institutions, :"管理番号", :"1"
	# rename_column :institutions, :"シーン種別(1)", :"2"
	# rename_column :institutions, :"シーン種別(2)", :"3"
	# rename_column :institutions, :"保障種別(2)", :"4"
	# rename_column :institutions, :"一般名称（今後増えてきたものにする）", :"5"
	# rename_column :institutions, :"独自（都、国、市町村）の呼称", :"6"
	# rename_column :institutions, :"保障額・保障内容", :"7"
	# rename_column :institutions, :"対象の方", :"8"
	# rename_column :institutions, :"年齢(以上)", :"9"
	# rename_column :institutions, :"年齢(以下)", :"10"
	# rename_column :institutions, :"年齢(偶数・奇数)", :"11"
	# rename_column :institutions, :"女", :"12"
	# rename_column :institutions, :"男", :"13"
	# rename_column :institutions, :"Unnamed:14", :"14"
	# rename_column :institutions, :"ひとり親", :"15"
	# rename_column :institutions, :"妊婦(産前産後)", :"16"
	# rename_column :institutions, :"Unnamed:17", :"17"
	# rename_column :institutions, :"子供(1)乳児", :"18"
	# rename_column :institutions, :"子供(2)就学前、保育園、幼稚園", :"19"
	# rename_column :institutions, :"子供(3)小学生", :"20"
	# rename_column :institutions, :"子供(4)中学生", :"21"
	# rename_column :institutions, :"子供(5)高校生", :"22"
	# rename_column :institutions, :"高齢者(1)前期高齢者対象", :"23"
	# rename_column :institutions, :"高齢者(2)後期高齢者対象", :"24"
	# rename_column :institutions, :"要介護者", :"25"
	# rename_column :institutions, :"障がい者", :"26"
	# rename_column :institutions, :"住宅・店舗", :"27"
	# rename_column :institutions, :"URL(1)", :"28"
	# rename_column :institutions, :"URL(2)", :"29"
	# rename_column :institutions, :"URL(3)", :"30"
	# rename_column :institutions, :"項目追加（1）", :"31"
	# rename_column :institutions, :"項目追加（2）", :"32"
	# rename_column :institutions, :"項目追加（3）", :"33"
  end
end
